import { RxDragHandleDots1 } from "react-icons/rx";
import {
  AiOutlineUser,
  AiOutlineClose,
  AiOutlineStar,
  AiOutlineMail,
  AiOutlineOrderedList,
  AiFillEye,
  AiFillMinusCircle,
  AiFillPlusCircle,
  AiFillSetting,
  AiFillCopy,
  AiFillDelete,
  AiFillHome,
  AiFillStar,
  AiOutlineSearch,
  AiOutlineHome,
  AiFillLock,
  AiFillUnlock,
} from "react-icons/ai";
import {
  BsFillPlayFill,
  BsFillPauseFill,
  BsArrowsCollapse,
  BsArrowsExpand,
  BsPalette,
  BsPaletteFill,
  BsPlayFill,
  BsFillPaletteFill,
  BsArrowRepeat,
  BsFillStopwatchFill,
  BsFillPencilFill,
  BsSnow,
  BsStar,
  BsStarFill,
} from "react-icons/bs";
import {
  MdExpandLess,
  MdExpandMore,
  MdSettings,
  MdTitle,
  MdSportsGymnastics,
} from "react-icons/md";
import {
  FaArrowAltCircleUp,
  FaArrowUp,
  FaEllipsisV,
  FaStepBackward,
  FaStepForward,
  FaWalking,
  FaStickyNote,
  FaSpinner,
} from "react-icons/fa";
import { TiDelete } from "react-icons/ti";
import { BiArrowBack } from "react-icons/bi";
import { GiWeightLiftingUp, GiSofa } from "react-icons/gi";
import { RxSpaceBetweenHorizontally } from "react-icons/rx";
import { TiTick } from "react-icons/ti";
import { LiaDumbbellSolid } from "react-icons/lia";

export {
  AiFillHome,
  AiOutlineHome,
  AiFillUnlock,
  AiFillCopy,
  AiOutlineStar,
  AiOutlineUser,
  AiFillDelete,
  AiOutlineMail,
  AiFillLock,
  AiOutlineOrderedList,
  AiOutlineSearch,
  AiFillSetting,
  AiOutlineClose,
  AiFillEye,
  AiFillStar,
  AiFillMinusCircle,
  AiFillPlusCircle,
  BiArrowBack,
  BsPlayFill,
  BsFillPlayFill,
  BsFillPencilFill,
  BsFillPauseFill,
  BsArrowRepeat,
  BsArrowsCollapse,
  BsArrowsExpand,
  BsFillStopwatchFill,
  BsSnow,
  BsPalette,
  BsPaletteFill,
  BsFillPaletteFill,
  BsStar,
  BsStarFill,
  FaWalking,
  FaEllipsisV,
  GiWeightLiftingUp,
  GiSofa,
  FaStepBackward,
  FaStepForward,
  FaStickyNote,
  FaSpinner,
  MdTitle,
  MdExpandLess,
  MdExpandMore,
  MdSettings,
  RxSpaceBetweenHorizontally,
  TiTick,
  TiDelete,
  MdSportsGymnastics,
  LiaDumbbellSolid,
  RxDragHandleDots1,
  FaArrowAltCircleUp,
  FaArrowUp,
};
